module.exports.Loader = require('./src/loader')
module.exports.Bindings = require('./src/bindings')
module.exports.BindingsLoader = require('./src/bindings-loader')
module.exports.Container = require('./src/container')
module.exports.Dependencies = require('./src/dependencies')
module.exports.Wrapper = require('./src/wrapper')